language: r
sudo: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
- tlmgr install fancyvrb units

r_packages:
- drat

after_success:
  - wget https://raw.githubusercontent.com/Osmahmoud/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

env:
  global:
    secure: hdE7fp33wWeRWiRw1IK/f3BuNK2zDWCjaSwrgXW6VRrygilL9GIAozy8ftD6LaTgBicl5OjWEWWX6osbVhF8j7qH+BbV5fHRN8fMeaDc22WiB0fVX7EzSx5uvjjMSo771tV4WE05WFyrsVtBDUAqUk3JWnMWOzjcOC9O37IwZGzKautaDwVYPxpgBkNOIryi5NqyPfkqAVyf3FYedaCiAxoDSP6M2n8v44ho3aeMlDhd5cZd7vEnwsdxEZMRyLndcCxD9dl7UQn6bDKPijQoRIu/BusPxkCzik0hEnJfPjXo6A09bnV0yHheUWVRJHADd7L746Ipd471pmLYT1+yu86bRBexgq40yXRHpcVDSZgD0GwsnTLaSAIMaXhAlDP/FUjpA/6NUtZmhC0MnmOJriCL77eIUYKNXrwJn4KbMf5V87MYJKIYrjrktzrIml4cMYLXXSv8UM56ltfyWVoeRragoBWe8VqQGiLcguN6g1Qjf+yt8vcwWIe8RfkMYLMXZEOrVl5H7Y9umxKXKPSIMgM8xlW9FCHJ2gqTzd79WdteM2Hovc0/RjmjWVHUQKWoZnjTa1zgxOrqxzBhbO0mdlT1FB5YvH070eRocPFHivDexB5Qkbf5MhZQA3kTf0LKW1o6EAzYn4GhDxi85MIikcBHK1iWQCHAF/hwPlDI6ow=
